### ISSUE TITLE
Have rolegiver check if the role is lower than makubot's role (so they can succeed in adding someone to the role)

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#144]

**Comment by lupomikti** [comment]
I'm not sure this is needed as the Manage Roles permission only allows one to manage roles lower than their highest role.
![image](https://user-images.githubusercontent.com/25500382/78417265-41325680-75e5-11ea-90da-edb911ebd6f7.png)

Perhaps you should instead handle the error given by an attempt to assign a role higher than makubot's? Alternatively, perhaps you might consider creating a managed role specifically for makubot that should be placed high in the role hierarchy by those who install it.

**Comment by makusu2** [comment]
@lupomikti I should have written this issue better, whoops; that's actually what I mean, I want to check whether Makubot would physically be able to grant a given role, so that the command can fail if I specify a role that's above Makubot's. (Right now, the command doesn't fail, due to how I have it set up, so there's no error to handle)

I might also suggest the second thing! I'd still like to fix this issue, just in case there *is* a case where someone tries to specify the highest role or whatever.
