### ISSUE TITLE
Additional role management functionality

### ISSUE THREAD

**Issue by lupomikti** [makusu2/makubot#145]
I think adding in functionality that allows administrators and/or moderators to assign roles using a command would be nice. Additionally, I would like to see rolegiver able to be used by admins/mods via the Manage Roles permission.

Role assignment via command would look like `mb.assign <Role> <User>` where `<Role>` accepts either the name of the role as text or an @ mention of the role, and where `<User>` is the ID string of the user as text or from @ mention. Only users with the Manage Roles permission should be able to use it.

**Comment by makusu2** [comment]
We can totally do `mb.assign`! I like it!

My fear with letting people other than me use mb.rolegiver is that there's a fair bit of complexity to roles, and I worry that someone could find a vulnerability in it. 

Would you be interested in doing a peer review of the rolegiver command? I'm worried about logic errors, not programming errors, so you don't need to be super familiar with discord.py to give your input. Plus, it might be helpful in learning how discord.py and asyncio works! 
https://github.com/makusu2/makubot/blob/master/src/rolegiver.py
Send me all the questions you have if you end up doing a review!
