### ISSUE TITLE
Change what happens when someone adds an existing image

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#159]
If someone uses `mb.addimage` with an image that's already in the collection, the image should have the current server added to its sids. That way, the image will start appearing in the new server.

**Comment by makusu2** [comment]
No, sids are a property of command, not image.
Hmm.

**Comment by makusu2** [comment]
@lupomikti Do you have any ideas?
If the "existing" image isn't associated with the user who tries to add it, they won't be able to pull the image even though they wanted to add it.

Maybe I should get rid of the duplicate image detector? Or only use it when the uid of the existing image equals the user who tried to add the duplicate image?

**Comment by lupomikti** [comment]
Are you sure SIDs aren't a property of images? That's what was planned in the media command insulation overhaul.

**Comment by makusu2** [comment]
@lupomikti I mean the origin sids, whoops

**Comment by lupomikti** [comment]
Potential solution is changing the `media.images` table's PK to be `(cmd, image_key, sid)`. This means that multiple images do not have to be physically stored, commands remain associated with their owners and origin servers, but the image can still be pulled on the non-origin server.

**Comment by makusu2** [comment]
(talking to myself)
We'll need to :
* Add `sid` to `media.images`'s PK like Lupo suggested
* For everything that has `select whatever from media.images`, group by sid or whatever, so we don't repeat images. 
* Make sure that every function that deletes rows will do what's expected if there are repeating images with different SIDs

**Comment by lupomikti** [comment]
With the removal of the complexity of the media insulation, does this still need to be addressed?

**Comment by makusu2** [comment]
Nope! :D
