### ISSUE TITLE
Add mb.nolike to  help command

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#217]

**Comment by lupomikti** [comment]
Help text should explain in it that this is an image blacklisting command so that it uses terms people are familiar with, and as such, `mb.imageblacklist` and the shorter forms (`mb.imgbl`, `mb.imgblacklist`, `mb.imagebl`) should be added as aliases.

**Comment by lupomikti** [comment]
Another thought: `mb.imageblacklist` and those aliases shouldn't alias `mb.nolike`. Instead, `mb.imageblacklist` should list the user's image blacklist, and `mb.imageblacklist [add|remove]` should be sub-commands. The `remove` sub-command should have the option of using numbers from the ordered list that `mb.imageblacklist` returns to the user. This means that `mb.nolike` will be a shorthand for `mb.imageblacklist add`. The shortened forms (`mb.imgbl` and so on) should still be implemented.

**Comment by makusu2** [comment]
I'm not sure it's worth adding the numbered list, because someone removing from their blacklist probably means either they just added it by mistake or want to take it back so they have the key right there anyway, or they've already done work to find out what the image key is. Since it's just going to be a lot of `lupo/unknown12.png`, I don't imagine having a shorter way of removing from the blacklist is very helpful.

**Comment by lupomikti** [comment]
That makes sense. I still think that `mb.imageblacklist` should say something like how many images they have blacklisted in that case and that `mb.nolike` is an alias of `mb.imageblacklist add` instead.

**Comment by makusu2** [comment]
Whoops, merged too fast, but I actually did exactly that lol
