### ISSUE TITLE
[Request] Make mb.poll send a message with the results of the poll instead of editing the original message, and explicitly mention the winning choice(s)

### ISSUE THREAD

**Issue by lupomikti** [makusu2/makubot#229]
`mb.poll` should send a message when the poll closes that summarizes the options and their vote totals while displaying the winning option emphasized (bolded perhaps?). An embed would be nice for this but not necessary. Deleting the poll would be nice but not necessary (thoughts on if this one is even a good idea?)

**Comment by lupomikti** [comment]
Oh, looking at the code it seems makubot already does something like this, just that when I tried to use timeout on my most recent poll it didn't update with the results at all. Then, to keep this on topic, do you think it'd be better change from editing the poll message to posting a new message?

**Comment by makusu2** [comment]
Ah yeah, it just broke when you used it (I fixed it in https://github.com/makusu2/makubot/pull/226/files#)
I feel like we should keep the poll (not delete it); even though people could react or unreact after the poll ends, it might be nice to get an idea for who voted what.

I like mentioning the winning (or tying) choices!

Yeah, editing the message or sending a new message with the results both seem fine, but if you think sending a new message would be better then I can totally do that.

**Comment by lupomikti** [comment]
Yeah, I think sending a new message with results and editing the original to say the poll is closed in some way would be a good idea.
