### ISSUE TITLE
Makubot isn't replacing embeds with video links again

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#233]
https://discordapp.com/channels/322509699159162883/579363357543497772/762076293322768404

The "image" link was https://makubot.s3.us-east-2.amazonaws.com/pictures/upisnotjump/video0-video00.mov

Why isn't it replacing with a video link?

**Comment by lupomikti** [comment]
Line 467 of picturecommands.py; Correct me if I'm wrong, but the url isn't empty when the embed fails to embed a video, right? In any case, I think this conditional statement is where the issue is because the one in `send_img_func` below it is different.

**Comment by makusu2** [comment]
I did some testing, and it turns out that it indeed ends up empty if it didn't accept the URL as an image (that's why it's worked to revert embeds to video URLs in the past).

But you're totally correct, nice eye! This is why you don't repeat code, whoops.

Thanks! :D
