### ISSUE TITLE
Makubot sent blank embed for mb.ramiel

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#242]
https://discordapp.com/channels/728688096299712544/728688096908148834/762760748014501899

Actual link was https://makubot.s3.us-east-2.amazonaws.com/pictures/ramiel/tumblr_n80m5hVPLr1rk1aixo4_250.gif
Are gifs not supported? Maybe we have to check against videos *and* gifs

**Comment by makusu2** [comment]
No, gifs work fine, hmmm

**Comment by makusu2** [comment]
And this specific gif is fine, too: https://discordapp.com/channels/@me/363949187445817346/762792027452342313

**Comment by lupomikti** [comment]
What's even more confusing is that the gif which broke the embed *has* worked in the past with no issue. My guess is that means it was something wrong with how the randomimage command did things compared to the send_image_func

**Comment by makusu2** [comment]
This one was actually invoked with mb.ramiel, so I don't think it's that. I tried doing mb.ramiel again, and I managed to get the same pic, and it worked fine, like you said. So I have no idea what happened :thinking:

**Comment by lupomikti** [comment]
Well, if it's not reproducible then I guess that's grounds for this issue to be closed. Can be reopened if it happens again.

**Comment by makusu2** [comment]
Fair enough!
