### ISSUE TITLE
Media command insulation overhaul

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#71]
There are major changes that will happen with media (image) commands (addimage). Images will be less open to all users, and more specific to the context in which the command is used.

For example, if two users do not know each other, are in two different servers, and have no servers in common, then an image that one adds should never be pulled for the second. 

The idea is to have a database that holds the following information:

Image: 
* `id`
    * ID of the image (primary key)
* `cmdid`
    * ID of the command from the command table.
* `uid`
    * ID of the user that added the image.
* `sid`
    * ID of the server in which the image was added.
    * null if there wasn't a server when the image was added (PMs or such). Updated to first server the image is pulled on.

Command:
* `id`
    * ID of the command (primary key)
* `uid`
    * ID of the user who added the first image to the command
* `origin_sids` 
    * List of IDs of the servers considered "origin" servers. 
    * Exactly equal to the set of servers that `uid` has executed the command on.

When `addimage myCommand myImage` is used, and then the image is approved by maku (`invoking_user` and `invoking_server` pulled from the context):
* If `myCommand` didn't exist, create a new command. Set `uid = invoking_user.id`. Set `origin_sids` to a single-element set containing the `invoking_server.id`, or an empty set if there is no applicable `invoking_server`
* Create a new image. Set `uid = invoking_user.id`. Set `cmdid = myCommand.id`. Set `sid` to `invoking_server.id`, or null if there was no applicable `invoking_server`.

When `mb.myCommand` is used, perform these IN ORDER (`invoking_user` and `invoking_server` pulled from the context):
* If `invoking_user.id == myCommand.uid`, and there is an applicable `invoking_server`, add `invoking_server.id` to `myCommand.origin_sids`. 
* Pull a random image which meet any of these qualifications
    * `img.uid == invoking_user.id`
    * `img.sid == invoking_server.id`
    * `img.sid in (invoking_user.servers & myCommand.origin_sids)`
* Treating `img` as the pulled image, if `img.uid == invoking_user.id` and `img.sid` is null, set `img.sid = invoking_server.id`.

Thoughts:
* Should the command table rows have a list of images that point to them? For efficiency? 
* It's a bit strange to have img.sid be set to the first server it's pulled on by the adding user. For instance, if I add an image to the "angry" command, there are probably a lot of images in there, so I won't pull it any time soon. Eventually I'll be in some random server and I'll pull it, making that server the sid of the image.

**Comment by makusu2** [comment]
This is one possible downside to having command "owners", although it really doesn't matter much:
Given a situation (case sensitive users/servers):
Server a: [User A User C]
Server b: [User B, User D]
Server c: [User A, User C]
Server d: [User B, User D]
User A adds an image to command CMD in server a. 
Later, user B adds an image to command CMD in server b. 
In server c, User A uses CMD (they get the image that user A added). 
In server d, User B uses CMD (they get the image that user B added). 
In server c, User A says to user C, "You should use this command, it's fun!". User C uses CMD and has fun.
In server d, User B says to user D, "You should use this command, it's fun!". User D uses CMD and is unable.
Despite the same steps being taken by both sets of users, only one was able to have fun because that set contained CMD's UID.

**Comment by makusu2** [comment]
Elaboration on previous post by a friend via Discord:

[3:15 PM] Leila: If A is the origitator: C can use it in a and c (a bc imd.sid matches cur_sid, c bc img.sid in intersection of user.servers and origin_sids). D can use it in b but not in d (b bc img.sid matches cur_sid for the image B added in b, not d bc img.sid doesn't match and user.servers intersect origin_sids is the empty set (none in common))
[3:16 PM] Leila: If B is the originator, then C can use it only in a (and only gets A's image) and D can use it in both b and d
[3:17 PM] Leila: If another user E is the originator (who is only in server e): C can only use it in a and D can only use it in b (bc those are the servers where A and B added the images) but C can't use it in c and D can't use it in d
[3:18 PM] Leila: This also assumes these two images are the only ones in the command so far. If C and D add images to it or A and B add images in c and d instead of just a and b, then there will be way more use for everyone and everyone has fun.
[3:19 PM] Leila: And if E ever joins any of the servers from a thru d then that further opens up more use

**Comment by makusu2** [comment]
@lupomikti was an incredible help for this plan, thank you so much <3333

**Comment by makusu2** [comment]
This could also help with the problem of losing image requests after a restart; we could save it by message ID instead. Although maybe that deserves its own issue

**Comment by makusu2** [comment]
This will make removing images much more difficult, as we'll need to either support a missing image path in the SQL pulling logic or we'll have to update the SQL table every time we delete an image

**Comment by makusu2** [comment]
It might make this task easier to write out the problems/questions we plan to encounter and the decision for handling them. Like for example, how we handle existing images.

**Comment by makusu2** [comment]
For existing images, we'll need to have some default/unknown value indicator in the columns (like a null value) and deal with it each time we're using the database, and for all existing images we'll add them to the database with those null values for the username and such.

**Comment by lupomikti** [comment]
I think it would be too much work to associate existing images with their command owners; but here's an idea: have a command that only you can use (like the alias command) that will assign command ownership to a specified user. That way a user can ask to take ownership of a command and you can approve and validate it. This would only need to be done for existing commands so once there are no commands with this "unowned" value in the table, you can remove this special command.

All images in a claimed command will have their `uid` set to that user as well; `origin_sids` should be left to previous logic, where it is equal to the set of servers the command is executed on by owner `uid`. Each image then uses the previous logic for `sid` assignment, where the first server the image gets pulled on becomes the image `sid`.

**Comment by makusu2** [comment]
@lupomikti There are enough images now that I don't foresee all commands getting assigned an owner any time soon (so I won't be able to remove the special command). The idea sounds perfect though, so that's how we'll handle that ^_^

What do you think should happen when a command/image has unknown values and we can't determine whether an image is relevant to the context? I don't think we should just never send the image, so do you think we should whitelist all images with unknown owner values?

**Comment by lupomikti** [comment]
Yeah that's what I was thinking. Everyone is currently used to the shared images and while the insulation will be nice when it's done, I don't think people would have an issue with those commands/images operating the same as they do now. So they should be allowed to post.

**Comment by makusu2** [comment]
All testing should be done on Makumistake. Do NOT apply an incomplete project to Makubot.

- [ ] Add code that creates blank tables (if not exist) for the above requirements
- [ ] Add some function to take all existing commands/images and populate the commands/images table, with null values as mentioned above.
- [ ] Add functionality that has some interaction with the database to only pull relevant commands (at this point, this will do nothing, as all existing commands/images have null values and we don't have functionality to add new images). It must act the same way as before, or something is wrong.
- [ ] Manually edit the tables to add some values, and test to make sure that the insulation logic is working correctly. It probably won't at first; fix any bugs.
- [ ] Add logic to create a new row on a new image/command addition. Ignore the user/server values; just make absolutely certain that new rows are being added and we aren't missing any. 
- [ ] Adjust the row addition logic above so that the user/server values are populated on image/command addition.
- [ ] Add logic for populating `img.sid`.
- [ ] Add logic for dealing with an image on S3 that isn't in the database for some reason.
- [ ] (Optional, maybe in a future ticket) Add logic for recognizing a missing image on S3 that exists in the database.
- [ ] Delete the existing database, then restart to make sure that we don't need to repeat the first few steps (since we now have logic for dealing with an image that isn't in the database).
- [ ] Apply to Makubot. This should just include pulling from master and restarting all containers. 

Once these steps are done, we can create new tickets with features that arise from this, such as the ability for a user to delete one of their images without asking Maku directly, and removing the dictionaries for keys and hashes (just use the database exclusively). These should happen after merging this into Makubot, though.

The order here is pretty important, as it'll make it easier to go at it one step at a time (which is important, since the size of this task is a big reason why I haven't done it yet)

**Comment by makusu2** [comment]
There should be a "sync" step on startup, where S3 is synced with the database.
If something exists on S3 but not on the database, add it to the database with null values.
If something exists on the database but not on S3, remove the row from the database and LOG IT. Or move it to some junk database.

**Comment by makusu2** [comment]
Keeping support for local images might overcomplicate this; maybe this is a good time to delete support for local images?

**Comment by makusu2** [comment]
If it's just Lupo, I don't mind giving S3 permissions to a bucket, so let's just delete local image support

**Comment by makusu2** [comment]
Let's remove the serial IDs from `images` and `image_commands` tables. Instead, let's have the primary keys be the image command (`lupo`) for `image_commands`, and for the `images` table, maybe we can have a compound key with the `image_commands` primary key and the string of the picture (`happy.jpg`)?

@lupomikti do compound keys work that way? Does a compound key have to be from two different primary keys, or can it be from a primary key and an arbitrary string?

**Comment by lupomikti** [comment]
I was thinking the command name would be the primary key for the commands anyway so that's fine. As far as my experience goes, a compound key is made of two or more primary keys from different tables (this is how you do Joins), so I don't believe using the command name and image file name will work.

I'm not sure how you are storing images per command at the moment but I was hoping that it be unique in some way. If not, then an auto-generated primary key is the best option. This is okay because none of the logic ever makes use of the image ID, it's purpose is only to be part of the table. When a random image is chosen, it can be one chosen from the set of images returned by the query `SELECT cmdid, uid, sid FROM images WHERE cmdid = <id_from_variable>` thus eliminating the importance of an `img_id`.

**Comment by makusu2** [comment]
Yeah, that's been my experience too, rip

The image keys are unique per command, but there might be a `happy.jpg` in `lupo` and another `happy.jpg` in `hatt`.

We could just do a string of command_name/image_key (so like `lupo/happy.jpg`), but that'd mean two sources of truth for the command name which is kinda icky.

I agree that an auto-generated ID would work, I'd just prefer to have something more useful be the primary key in the interest of less complexity. Hmm

**Comment by lupomikti** [comment]
If the command names are unique and image names are unique within the commands, then the idea of combining the command and file name is the best one we have. I'd use an underscore and treat it like a new file name instead of file path so it would end up `lupo_happy.jpg` and `hatt_happy.jpg`. That might feel a little cleaner, at least it does to me, though of course that's a bit subjective.

**Comment by makusu2** [comment]
Actually, we can! I just read this, we just gotta set the primary key to a combination of `cmd_name` and `image_name`. https://www.postgresqltutorial.com/postgresql-primary-key/
Woo \o/

**Comment by lupomikti** [comment]
Perfect, and even better it seems that you **can** use a column that's part of a primary key as a foreign key: https://www.postgresqltutorial.com/postgresql-foreign-key/

**Comment by makusu2** [comment]
(To self; I speak in third person in github stuff)
I'm thinking `add_pictures_dir` should check whether it's in the database and update the database if it's not there.
There should be some logic at the end of `ReactionImages`'s current `__init__` function, something like `sync_s3_to_db` that goes through all the images and ensures that they exist in the database, adding if they don't.
Then we'll also have to add logic to `apply_image_approved` that's similar to the logic we added to `add_pictures_dir`, where it checks whether it's in the images table and adds if it's not.

**Comment by lupomikti** [comment]
There is no way to (easily and clearly) store a set in postgresql, so we need a way to avoid duplicates in the `origin_sids` array field (or we normalize the database and make this field a table instead with `sid` and `cmdid` the primary key and only two fields).

You could continue to use an array and have external logic that checks for duplicates, or you could normalize the database and not use an array at all. Which do you think should be done?

**Comment by makusu2** [comment]
So the table would be something like `server_command_associations`, hmm... I think that's the best choice :+1: 
Good catch!

**Comment by lupomikti** [comment]
Okay, so just to be sure, the database now looks like the following (minus a field that sores the image path or some other way of accessing the image):

`TABLE images : id (string, pk), cmdid (string, pk, fk), uid (string), sid (string)`
`TABLE commands : id (string, pk), uid (string)`
`TABLE server_command_associations : sid (string, pk), cmdid (string, pk, fk)`

I also want to suggest that these tables be created under a new schema like the following:
```
CREATE SCHEMA IF NOT EXISTS pictures
  CREATE TABLE images (...)
  CREATE TABLE commands (...)
  CREATE TABLE server_command_associations (...);
```

**Comment by makusu2** [comment]
Almost, I've made some changes actually
```sql
CREATE TABLE IF NOT EXISTS image_commands (
cmd TEXT PRIMARY KEY,
uid CHARACTER(18),
origin_sids CHARACTER(18)[]);
```
```sql
CREATE TABLE IF NOT EXISTS images (
cmd TEXT REFERENCES image_commands(cmd),
image_key TEXT,
uid CHARACTER(18),
sid CHARACTER(18),
PRIMARY KEY (cmd, image_key));
```
`image_key` would be `happy.jpg`, `cmd` would be `lupo`.
I decided to name the table `image_commands` just to make it more clear, since anything that activates Makubot is a "command".
For the image_commands table, the way `origin_sids` works is going to change, based on what you said earlier.
I'll absolutely create a schema, good idea! I'll also include the existing `alias_images` table in it :+1: 
Actually, if it's in a `pictures` schema, should I just name the `image_commands` table `commands`? I wonder if that's best practice, or should I keep the more elaborate table name :?
Does that look good to you? Let me know, I'm going to make a new master post with the changes we've made

**Comment by makusu2** [comment]
Hmm, with the schema, if I want to add a new table to it it'd be more difficult than just adding another `CREATE TABLE IF NOT EXISTS`, since the `IF NOT EXISTS` part applies to the schema, not the tables it contains.
Probably still worth it though.

**Comment by makusu2** [comment]
Also, while we're at it, what do you think of the question I posed in the original issue: `Should the command table rows have a list of images that point to them? For efficiency?`?
I'm thinking that's not at all worth it, right?

**Comment by lupomikti** [comment]
Creation of a table within the schema will mostly be the same, you just have to prefix the table name with the schema name and dot notation. So `CREATE TABLE IF NOT EXISTS media.commands (...)` creates a table named 'commands' in the 'media' schema (namespace basically). I'm not sure on if it's better practice to keep the more descriptive name, I'll leave that up to you.

I don't think we need to have the list of images in the command table because we already have an images table with the command id as a foreign key. All we'd have to do is the appropriate JOIN and then each image would become accessible from its command (a lookup basically).

Now, as for the images table, are you able to use `image_key` to get the image? I'm not familiar yet with how images are stored and accessed. Will we be migrating the images from their existing location to these new tables? Does that mean we should have a field that stores the image file path? I'm just a little in there dark on this part.

**Comment by makusu2** [comment]
My issue with the schema thing is that if I go from (the difference being the addition of the aliases table):
```sql
CREATE SCHEMA IF NOT EXISTS pictures
    CREATE TABLE IF NOT EXISTS images (
        cmd TEXT REFERENCES commands(cmd),
        image_key TEXT,
        uid CHARACTER(18),
        sid CHARACTER(18),
        md5 TEXT,
        PRIMARY KEY (cmd, image_key))
    CREATE TABLE IF NOT EXISTS commands (
        cmd TEXT PRIMARY KEY,
        uid CHARACTER(18))
    CREATE TABLE IF NOT EXISTS server_command_associations (
        sid CHARACTER(18),
        cmd TEXT REFERENCES commands(cmd))
```
to
```sql
CREATE SCHEMA IF NOT EXISTS pictures
    CREATE TABLE IF NOT EXISTS images (
        cmd TEXT REFERENCES commands(cmd),
        image_key TEXT,
        uid CHARACTER(18),
        sid CHARACTER(18),
        md5 TEXT,
        PRIMARY KEY (cmd, image_key))
    CREATE TABLE IF NOT EXISTS commands (
        cmd TEXT PRIMARY KEY,
        uid CHARACTER(18))
    CREATE TABLE IF NOT EXISTS server_command_associations (
        sid CHARACTER(18),
        cmd TEXT REFERENCES commands(cmd))
    CREATE TABLE IF NOT EXISTS aliases (
        alias TEXT PRIMARY KEY,
        real TEXT);
```
The aliases table will not get created, despite its addition, since the code will get to `CREATE SCHEMA IF NOT EXISTS` and won't go any further since the schema does exist.
Is my logic there right?

The image key along with the command can get us the image. It's a little different, but it's organized in a way similar to a directory, where I'm looking at the file at location `pictures/lupo/happy.jpg`.

**Comment by lupomikti** [comment]
Oh, in that case, you only have to create the schema once since you don't have to create tables and views and stuff at the time of schema creation; you can create tables within a schema without having to do it in `CREATE SCHEMA`. Just prefix all the table names with the schema name.

**Comment by makusu2** [comment]
Ah, that works!

**Comment by makusu2** [comment]
I gave the middle finger to the checklist. 

- [ ] Add a check that if alias_images exists outside of the schema, somehow move it inside the schema. This can be removed after makubot is running and everything is merged.
- [ ] Remove dictionaries for keys and hashes
- [ ] Add logic for recognizing a missing image on S3 that exists in the database, and delete it from the database (log it)
- [ ] FUCKTON of solo testing
- [ ] Test Lupo's ABCD test
- [ ] Copy Makubot's newest database backup to Makumistake's bucket, start up Makumistake, make sure it works
- [ ] Apply to Makubot. This should just include pulling from master and restarting all containers.

**Comment by makusu2** [comment]
See if adding to the list of aliases allows the alias to be called, else do `self.bot.all_commands[ref_invocation] = true_invocation_command`

Also removing pictures_commands, just use the get all function.

**Comment by makusu2** [comment]
Image approvals are taking a while, see if you can speed it up

**Comment by makusu2** [comment]
"We haven't broken shit" tests:
- [ ] Random image works
- [ ] Named cmd works
- [ ] Alias works
- [ ] New image gets added correctly
- [ ] Aliasing works
- [ ] Bigten works
- [ ] Howbig works
- [ ] Something missing in S3 gets deleted from database
- [ ] Something missing in database gets added to it
- [ ] Duplicate image fails
- [ ] List_reactions works

**Comment by makusu2** [comment]
We should also do a speed comparison

**Comment by makusu2** [comment]
Add commands `set_cmd_owner` and `set_img_owner` that you can use whenever to set the `uid` of cmds and images. Actually, just make `set_cmd_images_owner` that applies to the command and all contained images.

**Comment by makusu2** [comment]
Data set tests:
- [ ] origin_sids gets updated when owner uses command in a new server
- [ ] origin_sids does not get updated when someone not the owner  uses command in a new server
- [ ] On new command, uid is set
- [ ] On new command, origin_sids is populated if in a guild
- [ ] On new command, sid is not set (empty) if not in a guild
- [ ] On new image, uid is set
- [ ] On new image, sid is set if in a guild
- [ ] On new image, sid is not set (null) if not in a guild

Insulation tests: 'A' adds command c1 with image i1 in 'a', 'B' adds image i2 to command c1 in 'b':
- [ ] 'A' is able to pull i1 in 'a'
- [ ] 'A' is able to pull i1 in 'b'
- [ ] A rando is able to pull i1 in 'a'
- [ ] If 'B' is not in 'a', 'B' is unable to pull i1 while in 'b'
- [ ] If 'B' is in 'a', 'B' is able to pull i1 while in 'b'
- [ ] If 'A' is in 'b', 'A' is able to pull i2 while in 'a'
- [ ] If 'A' is not in 'b', 'A' is unable to pull i2 while in 'a'

ABCD test:
Server a: [User A User C]
Server b: [User B, User D]
Server c: [User A, User C]
Server d: [User B, User D]
User A adds an image to command CMD in server a.
Later, user B adds an image to command CMD in server b.
In server c, User A uses CMD (they get the image that user A added).
In server d, User B uses CMD (they get the image that user B added).
- [ ] In server c, user C uses CMD and can get user A's image
- [ ] In server d, user D uses CMD and cannot get user B's image

**Comment by makusu2** [comment]
We should just only use ints for uids and sids, but store them as characters, and have logic for handling them either way in each method that calls SQL stuff.

**Comment by makusu2** [comment]
Fix issue where origin SIDs are getting duplicated

**Comment by makusu2** [comment]
- [ ] Test all the new commands with BS inputs
- [ ] Only use ints for uids and sids, but store them as characters, and have logic for handling them either way in each method that calls SQL stuff
- [ ] Bulkify what you can
- [ ] Speed comparison
- [ ] ABCD test
- [ ] Copy Makubot's newest database backup to Makumistake's bucket, start up Makumistake, make sure it works
- [ ] Apply to Makubot. This should just include pulling from master and restarting all containers.
- [ ] Manually add values to existing commands with setcmdowner

**Comment by makusu2** [comment]
At the moment, the only bulk job would be when when we load up from S3 for the first time and it has to add a lot, and even that doesn't take very long. I'm going to put off bulkifying requests until later, since hopefully synchronous operation will be easier to debug.

**Comment by makusu2** [comment]
There appears to be no significant difference in speed for image pulls, image additions, bigten, or howbig.

**Comment by makusu2** [comment]
E test was fukin crazy but everything worked exactly as expected

**Comment by makusu2** [comment]
Server message:

Hey everyone! Exciting Makubot news!
A big complaint about Makubot that I get is that people often pull images they didn't expect to pull, from other servers. 
This is no longer an issue! Now, commands should be insulated; for the most part, you'll only get images that are relevant to you when you call a command. 
This doesn't apply to mb.hey; those images are pulled entirely randomly from everywhere. 

I do need your help, though; if you have commands that you consider to be "yours", please send me a message with a list of them. This should really only be ones that only you have added images to, though.
Another important note is that if you want other people on AAGShit to pull your image, make sure to add the image on AAGShit, not in PMs or a special individual server! If you don't, there's a good chance it'll take a while before anyone pulls it. We have botspam for a reason!
The first server a command or image gets used on is important, so try to make AAGShit the first!

Huge thanks to Lupo; they spent so much time and effort helping me with this. They're freakin amazing, and this would never have gotten done if not for them. Thank you so much <3
Also, thanks to Phyro for helping us test!


(remember to tag channels and users)

**Comment by makusu2** [comment]
Planned release date: Wed April 7 18:00 Eastern

**Comment by makusu2** [comment]
Aliases aren't transferring correctly

**Comment by makusu2** [comment]
Aliases fixed

**Comment by makusu2** [comment]
DAB on this issue :dab:
